### ISSUE TITLE
Typo in my name

### ISSUE THREAD

**Issue by rslaugesen** [INMAS-Math/INMAS-Math#1]
Hi Martin, 
Typo in my last name on the "INMAS" repository: should be Laugesen.
Thanks,
   Rick

**Comment by INMAS-Math** [comment]
No charge for the extra 'n'.

From: rslaugesen ***@***.***>
Sent: Friday, November 3, 2023 21:14
To: INMAS-Math/INMAS-Math ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [INMAS-Math/INMAS-Math] Typo in my name (Issue #1)


      External Email - Use Caution





Hi Martin,
Typo in my last name on the "INMAS" repository: should be Laugesen.
Thanks,
Rick

-
